---
- hosts: all
  become: true
  vars:
    mysql_root_password: 1234
    mysql_db: wordpress
    mysql_user: wordpress_user
    mysql_password: wordpress_password
    wordpress_version: 6.0.3

  tasks:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apache2
        - mysql-server
        - php
        - php-mysql
        - libapache2-mod-php
        - php-xml
        - php-mbstring
        - php-curl
        - php-zip

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Set the root password for MySQL
      mysql_user:
        name: root
        password: 1234
        login_host: localhost
        login_user: root
        login_password: 1234

    - name: Create database for WordPress
      mysql_db:
        name: "{{ mysql_db }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user for WordPress
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_db }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/wordpress-{{ wordpress_version }}.tar.gz"
        dest: /tmp/wordpress.tar.gz

    - name: Unpack WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set ownership for WordPress files
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Set permissions for WordPress directories
      command: find /var/www/html/wordpress -type d -exec chmod 750 {} \;

    - name: Set permissions for WordPress files
      command: find /var/www/html/wordpress -type f -exec chmod 640 {} \;

    - name: Set up wp-config.php
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/html/wordpress/wp-config.php"

