#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: 1234
mysql_db: "wordpress"
mysql_user: "root"
mysql_password: 1234

#HTTP Settings
http_host: 192.168.56.6
http_conf: "your_domain.conf"
http_port: "80"
